version: "3"
services:
  # this container will run Cypress test using Chrome browser
  e2e-chrome:
    image: "cyp-dock-mocha-report"
    command: "test"
    volumes:
      - ./cypress/videos:/cypress-docker/cypress/videos
     # - ./cypress/reports:/cypress-docker/cypress/reports
      - ./cypress/mochawesome-report:/cypress-docker/mochawesome-report/
